version: '3.7'

networks:
  lemp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: lemp_nginx
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx-error.log:/var/log/nginx/error.log
      - ./logs/nginx-access.log:/var/log/nginx/access.log
    networks:
      - lemp

  mysql:
    image: mysql:latest
    container_name: lemp_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lemp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lemp

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: lemp_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - lemp

  pma:
    image: phpmyadmin:latest
    container_name: lemp_pma
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    networks:
      - lemp


